import type { ListKey, ListKeyFn, ListOptions } from '@/types';

export type { ListKey, ListKeyFn };

/**
 * Lifecycle flags representing the status of an item during reconciliation.
 *
 * Logic:
 * - Unchanged: Perfect match in both key and data; no action needed.
 * - Existing: Key matched, but position or data might need a patch/update.
 * - New: The item is completely new to this list.
 * - ForceReplace: Key matched, but data changed and no update handler is available
 *   to patch the node, requiring a full re-create.
 */
export const ItemState = {
  Unchanged: 0,

  Existing: 1 << 0,

  New: 1 << 1,

  ForceReplace: 1 << 2,
} as const;

export type ItemState = (typeof ItemState)[keyof typeof ItemState];

/**
 * The 'reconciliation plan' generated by the diffing algorithm.
 *
 * Provides index-based maps and metadata to the DOM synchronizer to
 * perform the minimum necessary DOM manipulations.
 */
export interface PreparedDiff<T> {
  newKeys: ListKey[];
  newItems: T[];
  newKeySet: Set<ListKey>;
  newIndices: number[];
  newStates: ItemState[];
  newNodes: (Element | JQuery | undefined)[];

  /** List of items requiring asynchronous DOM creation or HTML parsing */
  toRender: { key: ListKey; item: T; index: number }[];

  /** Indices defining the "dirty" middle section after prefix/suffix matching */
  startIndex: number;
  oldEndIndex: number;
  newEndIndex: number;
}

/**
 * Internal collection of hooks and callbacks used during the node placement phase.
 */
export interface PlaceCallbacks<T> {
  bind?: (($el: JQuery, item: T, index: number) => void) | undefined;
  update?: (($el: JQuery, item: T, index: number) => void) | undefined;
  onAdd?: (($el: JQuery) => void) | undefined;
  onRemove?: ListOptions<T>['onRemove'] | undefined;
  events?: ListOptions<T>['events'] | undefined;
}
