/**
 * @module List Types
 *
 * Responsibility:
 * Defines the core data structures and lifecycle states used by the list
 * reconciliation engine.
 *
 * Design Intent:
 * Decouples the diffing algorithm from the physical DOM synchronizer by
 * providing a unified 'PreparedDiff' schema.
 */

import type { ListKey, ListKeyFn, ListOptions } from '@/types';

export type { ListKey, ListKeyFn };

/**
 * Enumeration of lifecycle flags representing the reconciliation status of a list item.
 *
 * These flags are used by the internal DOM synchronizer to determine the minimum
 * required action (skipping, patching, or re-rendering) for each element.
 *
 * When to use:
 * - Internal orchestration of DOM updates within the `atomList` binding engine.
 *
 * @internal
 */
export const ItemState = {
  /**
   * Logic: The item's key and data are identical to the previous state.
   * Optimization: No DOM manipulation is required; this is the fastest execution path.
   */
  Unchanged: 0,

  /**
   * Logic: The key has been identified in the previous state, but its position
   * or data may require a patch or an update callback execution.
   */
  Existing: 1,

  /**
   * Logic: The item's key was not found in the previous state.
   * Action: A fresh DOM node must be created and inserted.
   */
  New: 2,

  /**
   * Logic: The key matched, but the item's data has changed and no custom
   * `update` callback was provided by the user.
   * Action: Requires a full destruction of the existing node followed by a
   * re-creation to ensure the DOM accurately reflects the new data.
   */
  ForceReplace: 3,
} as const;

export type ItemState = (typeof ItemState)[keyof typeof ItemState];

/**
 * Role: Reconciliation Metadata
 * Represents a single item's reconciliation state and metadata.
 *
 * @internal
 */
export interface DiffSlot<T> {
  /** The unique key for the item. */
  key: ListKey;
  /** The current data item. */
  item: T;
  /** The assigned reconciliation state. */
  state: ItemState;
  /** The index in the previous state, or -1 if new. */
  oldIndex: number;
  /** The index in the new state. */
  targetIndex: number;
  /** The current DOM handle. */
  node: Node[] | undefined;
}

/**
 * Role: Atomic Mutation Plan
 * A reconciliation plan generated by the diffing algorithm.
 *
 * Logic: Table-driven reconciliation
 * Provides a unified table of item slots and metadata required by the DOM
 * synchronizer to perform atomic mutations.
 *
 * @internal
 */
export interface PreparedDiff<T> {
  /** The unified collection of item slots. */
  slots: DiffSlot<T>[];
  /**
   * A collection of slots that require new DOM construction or HTML parsing.
   */
  toRender: DiffSlot<T>[];
  /** The new index map generated during the diff process. */
  keyToIndex: Map<ListKey, number>;
}

/**
 * A collection of user-provided lifecycle hooks and event configurations.
 *
 * @internal
 */
export interface PlaceCallbacks<T> {
  /** Invoked once when an element is first bound to a reactive item. */
  bind?: (($el: JQuery, item: T, index: number) => void) | undefined;
  /** Invoked on subsequent updates when item data changes. */
  update?: (($el: JQuery, item: T, index: number) => void) | undefined;
  /** Invoked when a new item is physically added to the DOM. */
  onAdd?: (($el: JQuery) => void) | undefined;
  /** Invoked to manage the removal of an item, supporting asynchronous transitions. */
  onRemove?: ListOptions<T>['onRemove'] | undefined;
  /** Delegated event listeners for the list container. */
  events?: ListOptions<T>['events'] | undefined;
}

/**
 * Normalization table for delegated event listeners.
 * @internal
 */
export interface EventBinding {
  type: string;
  selector: string;
  // biome-ignore lint/suspicious/noExplicitAny: generic callback with arbitrary signature
  callback: (...args: any[]) => any;
}
