import type { ListKey, ListKeyFn, ListOptions } from '@/types';

export type { ListKey, ListKeyFn };

/**
 * Lifecycle flags representing the status of an item during reconciliation.
 *
 * When to use:
 * - Determining the necessary DOM action (skip, patch, or re-render) for a list item.
 *
 * @internal
 */
export const ItemState = {
  /**
   * Logic: Perfect match in both key and data.
   * Benefit: No DOM action required; fastest path.
   */
  Unchanged: 0,

  /**
   * Logic: Key matched, but position or data might need a patch/update.
   */
  Existing: 1 << 0,

  /**
   * Logic: The item is completely new to this list.
   */
  New: 1 << 1,

  /**
   * Logic: Key matched, but data changed and no `update` handler is available.
   * Result: Requires a full destruction and re-creation of the node.
   */
  ForceReplace: 1 << 2,
} as const;

export type ItemState = (typeof ItemState)[keyof typeof ItemState];

/**
 * The 'reconciliation plan' generated by the diffing algorithm.
 *
 * Logic: Provides index-based maps and metadata to the DOM synchronizer to
 * perform the minimum necessary DOM manipulations.
 *
 * @internal
 */
export interface PreparedDiff<T> {
  newKeys: ListKey[];
  newItems: T[];
  newKeySet: Set<ListKey>;
  newIndices: number[];
  newStates: ItemState[];
  newNodes: (Element | JQuery | undefined)[];

  /** List of items requiring asynchronous DOM creation or HTML parsing */
  toRender: { key: ListKey; item: T; index: number }[];

  /** Indices defining the "dirty" middle section after prefix/suffix matching */
  startIndex: number;
  oldEndIndex: number;
  newEndIndex: number;
}

/**
 * @internal
 */
export interface PlaceCallbacks<T> {
  bind?: (($el: JQuery, item: T, index: number) => void) | undefined;
  update?: (($el: JQuery, item: T, index: number) => void) | undefined;
  onAdd?: (($el: JQuery) => void) | undefined;
  onRemove?: ListOptions<T>['onRemove'] | undefined;
  events?: ListOptions<T>['events'] | undefined;
}
